spring:
  application:
    name: minecraftmanager

  datasource:
    url: jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_DB:minecraft-manager}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    locations: classpath:db/migration

  server:
    port: ${SERVER_PORT:8080}

  servlet:
    multipart:
      max-file-size: 5GB
      max-request-size: 5GB

minecraft:
  worlds-directory: minecraft-data/worlds
  host: ${MINECRAFT_HOST:localhost}
  port-range:
    start: ${PORT_RANGE_START:30000}
    end: ${PORT_RANGE_END:40000}
