ALTER TABLE worlds
    ADD COLUMN container_id VARCHAR(120),
    ADD COLUMN status VARCHAR(30) NOT NULL DEFAULT 'CREATED',
    ADD COLUMN game_mode VARCHAR(20) NOT NULL DEFAULT 'SURVIVAL',
    ADD COLUMN difficulty VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    ADD COLUMN seed VARCHAR(100);
