ALTER TABLE worlds
    ADD COLUMN memory_mb INTEGER NOT NULL DEFAULT 2048,
    ADD COLUMN max_players INTEGER NOT NULL DEFAULT 20,
    ADD COLUMN view_distance INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN simulation_distance INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN motd VARCHAR(250) NOT NULL DEFAULT 'A Minecraft Server';
